[custom.all.cptr]
type = "github"
url = "https://github.com/pitype-os/idris2-cptr"
commit = "b22fa4148865135216e9fcd5670fcb91af41be7f"
ipkg = "cptr.ipkg"

[idris2]
bootstrap = true
url = "https://github.com/pitype-os/Idris2"
commit = "052bd2390714228fe48f5805188c2ae32023a4c5"
