[custom.all.cptr]
type = "github"
url = "https://github.com/pitype-os/idris2-cptr"
commit = "f39eb767d54185e5f55418bfc7acb19df559b569"
ipkg = "cptr.ipkg"

[idris2]
bootstrap = true
url = "https://github.com/pitype-os/Idris2"
commit = "6dbff908544229b55c72a700706d1eeeb29b9c92"
