[custom.all.cptr]
type = "github"
url = "https://github.com/pitype-os/idris2-cptr"
commit = "74c9fa998ad7e5ba80c10583acb743f65e6c28f3"
ipkg = "cptr.ipkg"

[idris2]
bootstrap = true
url = "https://github.com/pitype-os/Idris2"
commit = "4adf1b841fe0248289b1ec4d6443a3688824d084"
