module VirtIO

import Uart

MMIO_VIRTIO_START : Bits64
MMIO_VIRTIO_START = 0x10001000

MMIO_VIRTIO_END : Bits64
MMIO_VIRTIO_END = 0x10008000

MMIO_VIRTIO_STATUS : Bits64
MMIO_VIRTIO_STATUS =  0x70

MMIO_VIRTIO_STRIDE : Bits64
MMIO_VIRTIO_STRIDE =  0x1000

MMIO_VIRTIO_MAGIC : Bits64
MMIO_VIRTIO_MAGIC = 0x74726976

export
probe : IO ()
probe = do
  for_[MMIO_VIRTIO_START, MMIO_VIRTIO_START+MMIO_VIRTIO_STRIDE..MMIO_VIRTIO_END] $ \x => 
    println $ show x
