name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    name: Deploy to staging environment
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
